permalink: pretty

exclude:
  - fa/src
  - fa/scss
  - fa/less
  - fa/*.json
  - fa/*.md
  - fa/*.txt
  - fa/Gem*

collections:
  - projects

defaults:
  -
    scope:
      paths: _posts
    values:
      layout: post


mobile-width: "600px"
